Update playwright.yml

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -23,11 +23,13 @@ jobs:
     - name: Debug Filesystem
       if: always()  
       run: ls
+    - name: Debug test-results Folder
+      run: ls -lah test-results || echo "test-results not found"
     - uses: actions/upload-artifact@v4
       if: always()  
       with:
         name: test-results
-        path: test-results/
+        path: ${{ github.workspace }}/test-results/
         retention-days: 30
     - name: Send Email
       if: always()  
