changes

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -23,13 +23,13 @@ jobs:
     - name: Debug Filesystem
       if: always()  
       run: ls
-    - name: Debug test-results Folder
-      run: ls -lah test-results || echo "test-results not found"
+    - name: Debug playwright-report Folder
+      run: ls -lah playwright-report || echo "playwright-report not found"
     - uses: actions/upload-artifact@v4
       if: always()  # Ensures it runs even if tests fail
       with:
-        name: test-results
-        path: ${{ github.workspace }}/test-results/
+        name: playwright-report
+        path: ${{ github.workspace }}/playwright-report/
         retention-days: 30
 
   send-email:
@@ -44,7 +44,7 @@ jobs:
       run: npm install
     - uses: actions/download-artifact@v4
       with:
-        name: test-results
-        path: test-results/
+        name: playwright-report
+        path: playwright-report/
     - name: Send Email
       run: npm run send-email
